package com.hormi.app.ui

/**
 * Traducción de nombres para mostrar: ligas y selecciones/clubes que la API trae en inglés
 * o sin acento. Si un nombre no está en la lista se muestra tal cual (por eso es seguro
 * aplicarla también a datos que el servidor ya tradujo).
 */
private val LIGAS_ES = mapOf(
    "Friendlies" to "Amistoso",
    "Friendlies Clubs" to "Amistoso de clubes",
    "Friendly International" to "Amistoso internacional",
    "Super League 1" to "Superliga de Grecia",
    "Super League" to "Superliga de Grecia",
    "World Cup" to "Copa del Mundo",
    "World Cup - U20" to "Mundial Sub-20",
    "World Cup - Qualification CONCACAF" to "Eliminatorias Concacaf",
    "Concacaf World Cup Qualifiers" to "Eliminatorias Concacaf",
    "World Cup - Qualification Intercontinental Play-offs" to "Repechaje intercontinental",
    "CONCACAF Nations League" to "Liga de Naciones Concacaf",
    "CONCACAF Gold Cup" to "Copa Oro",
    "Gold Cup" to "Copa Oro",
    "CONCACAF Champions League" to "Liga de Campeones Concacaf",
    "Leagues Cup" to "Leagues Cup",
    "UEFA Champions League" to "Liga de Campeones",
    "UEFA Europa League" to "Europa League",
    "UEFA Europa Conference League" to "Conference League",
    "Copa America" to "Copa América",
    "League Cup" to "Copa de la Liga",
    "FA Cup" to "Copa FA",
    "Super Cup" to "Supercopa",
    "Coppa Italia" to "Copa Italia",
    "Primeira Liga" to "Liga Portugal",
    "Taça de Portugal" to "Copa de Portugal",
    "KNVB Beker" to "Copa de Países Bajos",
    "Major League Soccer" to "MLS",
    "MLS All-Star" to "Juego de Estrellas MLS",
    "Campeones Cup" to "Campeones Cup",
    "US Open Cup" to "Copa Abierta de EE. UU.",
    "Pro League" to "Liga Profesional Saudí",
    "Olympics Men" to "Juegos Olímpicos",
    "Olympics Men - Qualification Concacaf" to "Preolímpico Concacaf",
    "Confederations Cup" to "Copa Confederaciones",
    "FIFA Club World Cup" to "Mundial de Clubes",
    "FIFA Intercontinental Cup" to "Copa Intercontinental",
    "Pan American Games" to "Juegos Panamericanos",
    "CAC Games" to "Juegos Centroamericanos",
    "Tournoi Maurice Revello" to "Torneo Maurice Revello",
    "CONMEBOL Libertadores U20" to "Libertadores Sub-20",
    "CONMEBOL U20" to "Sudamericano Sub-20",
    "AFC Champions League Elite" to "Liga de Campeones de Asia",
    "Premier League - Summer Series" to "Premier League Summer Series",
    "International Champions Cup" to "Copa Internacional de Campeones",
    "King's Cup" to "Copa del Rey de Arabia",
    "Eerste Divisie" to "Eerste Divisie",
    "Championship" to "Championship",
    "Eredivisie" to "Eredivisie",
)

private val EQUIPOS_ES = mapOf(
    "Mexico" to "México",
    "USA" to "Estados Unidos",
    "United States" to "Estados Unidos",
    "Canada" to "Canadá",
    "Panama" to "Panamá",
    "Peru" to "Perú",
    "Brazil" to "Brasil",
    "Germany" to "Alemania",
    "Spain" to "España",
    "France" to "Francia",
    "England" to "Inglaterra",
    "Italy" to "Italia",
    "Netherlands" to "Países Bajos",
    "Belgium" to "Bélgica",
    "Switzerland" to "Suiza",
    "Poland" to "Polonia",
    "Denmark" to "Dinamarca",
    "Sweden" to "Suecia",
    "Norway" to "Noruega",
    "Croatia" to "Croacia",
    "Scotland" to "Escocia",
    "Wales" to "Gales",
    "Czech Republic" to "Chequia",
    "Czechia" to "Chequia",
    "Hungary" to "Hungría",
    "Greece" to "Grecia",
    "Turkey" to "Turquía",
    "Austria" to "Austria",
    "Ireland" to "Irlanda",
    "Japan" to "Japón",
    "South Korea" to "Corea del Sur",
    "Korea Republic" to "Corea del Sur",
    "China" to "China",
    "Saudi Arabia" to "Arabia Saudita",
    "Iran" to "Irán",
    "Iraq" to "Irak",
    "Qatar" to "Catar",
    "Morocco" to "Marruecos",
    "Egypt" to "Egipto",
    "Tunisia" to "Túnez",
    "Algeria" to "Argelia",
    "Cameroon" to "Camerún",
    "Ivory Coast" to "Costa de Marfil",
    "South Africa" to "Sudáfrica",
    "New Zealand" to "Nueva Zelanda",
    "Haiti" to "Haití",
    "Jamaica" to "Jamaica",
    "Olympiakos Piraeus" to "Olympiakos",
    "Atletico Madrid" to "Atlético de Madrid",
    "Alaves" to "Alavés",
    "Maritimo" to "Marítimo",
    "FC Copenhagen" to "FC Copenhague",
)

fun ligaEs(name: String?): String? = name?.let { LIGAS_ES[it] ?: it }

fun equipoEs(name: String?): String? = name?.let { EQUIPOS_ES[it] ?: it }
